### ISSUE TITLE
Commands::Delegate carries no generation/boot-id fields, so fork-#358's fail-closed guard doesn't cover it

### ISSUE THREAD

**Issue by prageethw** [prageethw/dot-agent-deck#567]
## Context

While auditing PR #555 (issue #461, `work-done`'s registration-generation/daemon-boot-id reader), the auditor found an out-of-scope, pre-existing gap worth tracking separately.

Fork issue #358 added a fail-closed guard so a `work-done` report is refused at delivery rather than silently accepted when it doesn't match the pane's current registration — enforced via a `(generation, daemon_boot_id)` pair read from env vars and checked in `handle_work_done` (`src/state.rs`).

`Commands::Delegate`'s own signal type (`DelegateSignal`) carries no such fields at all — no generation, no boot id — so the same class of stale-signal problem #358 closed for `work-done` is entirely unprotected on the `delegate` path.

## Why this matters

A delegate signal delivered after the pane's registration has moved on (daemon restart, pane reuse, orchestration replaced) has nothing analogous to #358's check to refuse it. This is the same shape of defect #358 fixed, just on the other CLI verb.

## Scope

Not introduced by PR #555 — pre-existing. Needs its own investigation: whether `DelegateSignal` should gain the same two fields, and how `handle_delegate` (or its equivalent) should enforce them, mirroring `handle_work_done`'s `(0, "")`-can't-match reasoning documented in PR #555's audit findings.

## Reference

Found during: PR #555 / issue #461 audit pass. Findings file: `.dot-agent-deck/findings-461-auditor.md` (root checkout), section "Out of scope, pre-existing, worth knowing."

**Comment by prageethw** [comment]
Claimed by @prageethw working from `agent-server` at 2026-09-12T00:59:31.291544218+00:00.
